// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onLatitudeChange();
void onLongitudeChange();

float latitude;
float longitude;
CloudLocation location;

void initProperties(){

  ArduinoCloud.addProperty(latitude, READWRITE, 20 * SECONDS, onLatitudeChange);
  ArduinoCloud.addProperty(longitude, READWRITE, 20 * SECONDS, onLongitudeChange);
  ArduinoCloud.addProperty(location, READ, 20 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
